export type Skill = 'Easy' | 'Comfortable' | 'Project';
export type Mood = 'Cosy' | 'Fresh' | 'Bright' | 'Hearty' | 'Quick';

export type Recipe = {
  id: string;
  title: string;
  description: string;
  time: number;
  skill: Skill;
  mood: Mood;
  category: string;
  ingredients: string[];
  pantryStaples: string[];
  method: string[];
  accent: string;
  searchTerms: string;
};

export const ingredientGroups = [
  {
    label: 'Produce',
    items: ['onion', 'garlic', 'tomato', 'spinach', 'lemon', 'carrot', 'potato', 'bell pepper', 'mushrooms', 'broccoli'],
  },
  {
    label: 'Fridge',
    items: ['eggs', 'cheddar', 'yogurt', 'butter', 'milk', 'feta', 'parmesan', 'tofu'],
  },
  {
    label: 'Cupboard',
    items: ['chickpeas', 'black beans', 'lentils', 'rice', 'pasta', 'flour', 'bread', 'coconut milk', 'tinned tomatoes'],
  },
] as const;

export const recipes: Recipe[] = [
  {
    id: 'golden-shakshuka',
    title: 'Golden Shakshuka',
    description: 'Jammy eggs tucked into a smoky tomato and pepper sauce.',
    time: 32,
    skill: 'Easy',
    mood: 'Bright',
    category: 'One pan',
    ingredients: ['eggs', 'tomato', 'bell pepper', 'onion', 'garlic'],
    pantryStaples: ['olive oil', 'paprika', 'cumin'],
    method: ['Soften onion and pepper in olive oil until glossy.', 'Add garlic, paprika and cumin, then pour in tomatoes.', 'Make wells, crack in eggs, cover and cook until just set.'],
    accent: '#e9a33b',
    searchTerms: 'golden shakshuka easy eggs tomato',
  },
  {
    id: 'feta-baked-eggs',
    title: 'Feta Baked Eggs',
    description: 'Soft baked eggs, salty feta and garlicky tomatoes for dipping.',
    time: 29,
    skill: 'Easy',
    mood: 'Bright',
    category: 'Bake',
    ingredients: ['eggs', 'tomato', 'feta', 'garlic', 'onion'],
    pantryStaples: ['olive oil', 'chilli flakes', 'bread'],
    method: ['Cook onion and garlic in olive oil until soft and sweet.', 'Add chopped tomatoes and simmer until saucy.', 'Nestle in eggs, dot with feta and bake until the whites set.'],
    accent: '#d97956',
    searchTerms: 'feta baked eggs tomato garlic',
  },
  {
    id: 'creamy-spinach-orzo',
    title: 'Creamy Spinach Orzo',
    description: 'A lemony, one-pot bowl with tender greens and a silky finish.',
    time: 24,
    skill: 'Easy',
    mood: 'Cosy',
    category: 'One pot',
    ingredients: ['spinach', 'garlic', 'lemon', 'parmesan', 'milk'],
    pantryStaples: ['orzo', 'vegetable stock', 'black pepper'],
    method: ['Toast the orzo with garlic in butter for two minutes.', 'Add stock and simmer, stirring, until the orzo is tender.', 'Fold through spinach, parmesan and lemon zest.'],
    accent: '#8eaf68',
    searchTerms: 'creamy spinach orzo lemon parmesan',
  },
  {
    id: 'crispy-chickpea-pitas',
    title: 'Crispy Chickpea Pitas',
    description: 'Roasted spiced chickpeas, cool yogurt and crunchy veg in warm bread.',
    time: 28,
    skill: 'Easy',
    mood: 'Fresh',
    category: 'Handheld',
    ingredients: ['chickpeas', 'yogurt', 'lemon', 'garlic', 'tomato'],
    pantryStaples: ['pita bread', 'cumin', 'olive oil'],
    method: ['Toss chickpeas with cumin and oil, then roast until crisp.', 'Stir garlic and lemon into yogurt for a quick sauce.', 'Fill warm pitas with chickpeas, tomato and sauce.'],
    accent: '#dc765b',
    searchTerms: 'crispy chickpea pitas yogurt',
  },
  {
    id: 'tomato-butter-beans',
    title: 'Tomato Butter Beans',
    description: 'Slow-simmered beans with garlic, greens and a bright spoonful of lemon.',
    time: 35,
    skill: 'Easy',
    mood: 'Hearty',
    category: 'Bowl',
    ingredients: ['tomato', 'garlic', 'spinach', 'onion'],
    pantryStaples: ['butter beans', 'olive oil', 'chilli flakes'],
    method: ['Cook onion slowly until sweet and soft.', 'Add garlic and tomatoes, then simmer until thick.', 'Fold in beans and spinach; finish with lemon and olive oil.'],
    accent: '#c86448',
    searchTerms: 'tomato butter beans spinach lemon',
  },
  {
    id: 'lemony-lentil-soup',
    title: 'Lemony Lentil Soup',
    description: 'A generous pot of red lentils, carrot and lemon for tomorrow too.',
    time: 42,
    skill: 'Easy',
    mood: 'Cosy',
    category: 'Soup',
    ingredients: ['lentils', 'carrot', 'onion', 'garlic', 'lemon'],
    pantryStaples: ['vegetable stock', 'cumin', 'olive oil'],
    method: ['Sweat onion and carrot with cumin until fragrant.', 'Add lentils and stock; simmer until creamy.', 'Blend one ladleful back in, then season with lemon.'],
    accent: '#d9a23f',
    searchTerms: 'lemony lentil soup carrot cumin',
  },
  {
    id: 'green-garlic-frittata',
    title: 'Green Garlic Frittata',
    description: 'Soft-centred eggs with wilted spinach and a salty feta edge.',
    time: 22,
    skill: 'Easy',
    mood: 'Fresh',
    category: 'Skillet',
    ingredients: ['eggs', 'spinach', 'garlic', 'feta', 'onion'],
    pantryStaples: ['butter', 'black pepper'],
    method: ['Soften onion and garlic in an oven-safe skillet.', 'Wilt in spinach, then pour over whisked eggs.', 'Scatter feta over the top and cook until barely set.'],
    accent: '#83a85c',
    searchTerms: 'green garlic spinach feta frittata',
  },
  {
    id: 'roasted-veg-pasta',
    title: 'Roasted Vegetable Pasta',
    description: 'Caramelised vegetables and parmesan cling to every curly noodle.',
    time: 38,
    skill: 'Comfortable',
    mood: 'Hearty',
    category: 'Pasta',
    ingredients: ['pasta', 'bell pepper', 'tomato', 'onion', 'garlic', 'parmesan'],
    pantryStaples: ['olive oil', 'dried herbs'],
    method: ['Roast vegetables with garlic and oil until browned at the edges.', 'Boil pasta, saving a mug of the starchy water.', 'Toss everything with parmesan and enough pasta water to gloss.'],
    accent: '#d8744c',
    searchTerms: 'roasted vegetable pasta parmesan',
  },
  {
    id: 'coconut-chickpea-curry',
    title: 'Coconut Chickpea Curry',
    description: 'A mellow, creamy curry with spinach that comes together in one pan.',
    time: 31,
    skill: 'Easy',
    mood: 'Hearty',
    category: 'One pan',
    ingredients: ['chickpeas', 'coconut milk', 'spinach', 'onion', 'garlic', 'tomato'],
    pantryStaples: ['curry powder', 'rice', 'oil'],
    method: ['Cook onion and garlic with curry powder until aromatic.', 'Add tomatoes, coconut milk and chickpeas; bubble until thick.', 'Stir in spinach and serve over rice.'],
    accent: '#e3a23b',
    searchTerms: 'coconut chickpea curry spinach',
  },
  {
    id: 'carrot-fritters',
    title: 'Carrot & Cheddar Fritters',
    description: 'Crisp-edged, tender fritters with a cool yogurt dip.',
    time: 27,
    skill: 'Comfortable',
    mood: 'Bright',
    category: 'Skillet',
    ingredients: ['carrot', 'cheddar', 'eggs', 'yogurt', 'garlic'],
    pantryStaples: ['flour', 'olive oil', 'cumin'],
    method: ['Grate carrots and squeeze out as much moisture as possible.', 'Mix with egg, cheddar, flour and cumin.', 'Fry spoonfuls until deeply golden, then serve with yogurt.'],
    accent: '#e09643',
    searchTerms: 'carrot cheddar fritters yogurt',
  },
  {
    id: 'pantry-tomato-rice',
    title: 'Pantry Tomato Rice',
    description: 'Fragrant rice cooked right in a garlicky tomato base.',
    time: 36,
    skill: 'Easy',
    mood: 'Cosy',
    category: 'One pot',
    ingredients: ['rice', 'tinned tomatoes', 'onion', 'garlic', 'bell pepper'],
    pantryStaples: ['vegetable stock', 'paprika', 'olive oil'],
    method: ['Soften pepper, onion and garlic with paprika.', 'Stir through rice and tinned tomatoes.', 'Add stock, cover and cook until the grains are tender.'],
    accent: '#cf6747',
    searchTerms: 'pantry tomato rice one pot',
  },
  {
    id: 'mushroom-toast',
    title: 'Miso Mushroom Toast',
    description: 'Bronzed mushrooms over buttered toast with a savoury, glossy glaze.',
    time: 18,
    skill: 'Easy',
    mood: 'Quick',
    category: 'Toast',
    ingredients: ['mushrooms', 'garlic', 'bread', 'butter'],
    pantryStaples: ['miso', 'soy sauce', 'olive oil'],
    method: ['Sear mushrooms in a hot pan until deeply browned.', 'Add butter, garlic and miso, tossing until glossy.', 'Pile onto toast and finish with black pepper.'],
    accent: '#9d7658',
    searchTerms: 'miso mushroom toast garlic',
  },
  {
    id: 'broccoli-cheddar-bake',
    title: 'Broccoli Cheddar Bake',
    description: 'A bubbling, crunchy-topped bake for the nights that need comfort.',
    time: 48,
    skill: 'Comfortable',
    mood: 'Hearty',
    category: 'Bake',
    ingredients: ['broccoli', 'cheddar', 'milk', 'garlic', 'onion'],
    pantryStaples: ['flour', 'butter', 'breadcrumbs'],
    method: ['Blanch broccoli until bright, then drain well.', 'Make a quick cheese sauce with butter, flour and milk.', 'Fold together, top with crumbs and bake until bubbling.'],
    accent: '#789c64',
    searchTerms: 'broccoli cheddar bake cheese sauce',
  },
  {
    id: 'warm-potato-salad',
    title: 'Warm Potato & Egg Salad',
    description: 'Crushed potatoes, jammy eggs and a mustardy lemon dressing.',
    time: 34,
    skill: 'Easy',
    mood: 'Fresh',
    category: 'Salad',
    ingredients: ['potato', 'eggs', 'onion', 'lemon', 'yogurt'],
    pantryStaples: ['mustard', 'olive oil', 'dried herbs'],
    method: ['Boil potatoes until tender and eggs until jammy.', 'Whisk lemon, yogurt, mustard and olive oil.', 'Toss warm crushed potatoes with dressing and top with eggs.'],
    accent: '#d9aa4c',
    searchTerms: 'warm potato egg salad lemon yogurt',
  },
  {
    id: 'tofu-pepper-stir-fry',
    title: 'Tofu Pepper Stir-fry',
    description: 'Crisp tofu and sweet peppers under a three-ingredient sauce.',
    time: 25,
    skill: 'Comfortable',
    mood: 'Quick',
    category: 'Wok',
    ingredients: ['tofu', 'bell pepper', 'garlic', 'onion', 'broccoli'],
    pantryStaples: ['soy sauce', 'rice', 'sesame oil'],
    method: ['Press and cube tofu, then sear until crisp on all sides.', 'Stir-fry peppers, onion and broccoli until just tender.', 'Return tofu with soy, sesame and garlic; serve with rice.'],
    accent: '#d87956',
    searchTerms: 'tofu pepper stir fry broccoli',
  },
  {
    id: 'spinach-dal',
    title: 'Spinach Dal',
    description: 'Creamy lentils tempered with garlic and folded with soft greens.',
    time: 44,
    skill: 'Comfortable',
    mood: 'Cosy',
    category: 'Pot',
    ingredients: ['lentils', 'spinach', 'onion', 'garlic', 'tomato'],
    pantryStaples: ['coconut milk', 'turmeric', 'rice'],
    method: ['Simmer lentils, tomatoes and turmeric until soft.', 'Cook onion and garlic separately until golden.', 'Fold in spinach and finish with the fragrant onion topping.'],
    accent: '#a3a04b',
    searchTerms: 'spinach dal lentils garlic',
  },
  {
    id: 'lemon-parmesan-pasta',
    title: 'Lemon Parmesan Pasta',
    description: 'The fast one: glossy noodles, bright lemon and a snowy parmesan finish.',
    time: 16,
    skill: 'Easy',
    mood: 'Quick',
    category: 'Pasta',
    ingredients: ['pasta', 'lemon', 'parmesan', 'garlic', 'butter'],
    pantryStaples: ['black pepper', 'olive oil'],
    method: ['Cook pasta until just shy of al dente, saving pasta water.', 'Bloom garlic in butter, then add lemon zest.', 'Toss pasta with parmesan and splashes of pasta water until glossy.'],
    accent: '#e7bd52',
    searchTerms: 'lemon parmesan pasta garlic',
  },
  {
    id: 'black-bean-quesadillas',
    title: 'Black Bean Quesadillas',
    description: 'Crisp tortillas, melty cheddar and spiced beans with fresh tomato.',
    time: 21,
    skill: 'Easy',
    mood: 'Quick',
    category: 'Skillet',
    ingredients: ['black beans', 'cheddar', 'tomato', 'onion', 'bell pepper'],
    pantryStaples: ['tortillas', 'cumin', 'olive oil'],
    method: ['Mash beans with cumin and a pinch of salt.', 'Layer beans, cheddar and sliced vegetables into tortillas.', 'Toast in a dry skillet until crisp and molten.'],
    accent: '#ce7256',
    searchTerms: 'black bean cheddar quesadillas',
  },
];